### PR TITLE
Notify polymer on user changed

### PR DESCRIPTION
**Pull request by rickmak**
It uses the skygear provided `onUserChanged` to notify the polymer side.

### CODE REVIEW

**Comment by seventhmoon** [comment]
Thank you. But this repo is for sample use.
I think there should be another repo for the Web Component ONLY. (so to submit to webcomponent.org)

Although I made one on https://github.com/astri-isns/polymersky, should there an official one from skygear-io?

**Comment by rickmak** [comment]
Sure, let me open an repo for you? name is...?

**Comment by seventhmoon** [comment]
the one for firebase is called polymerfire, with components firebase-app, firebase-auth.
shall it be polymersky, with components skygear-app...etc? 
or MilkTea, Coffee LOL

**Comment by chpapa** [comment]
Sure, and would you be interested be the maintainer of the repo? :) @seventhmoon

**Comment by seventhmoon** [comment]
If you don't mind I am a newbie.
(My first week with Polymer)

**Comment by rickmak** [comment]
I created: https://github.com/SkygearIO/polymersky

**Pull request merged**
